"""
gen_nb.py — Generates code.ipynb for Week 5 Day 2: LangChain agent
"""
import json, os

def code_cell(src):
    return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":src}

def md_cell(src):
    return {"cell_type":"markdown","metadata":{},"source":src}

cells = []

# ── HEADER ────────────────────────────────────────────────────────────────────
cells.append(md_cell([
    "# Week 5 Day 2 — LangChain: Tools, Chains, Memory & Framework Agents\n",
    "\n",
    "> **Goal:** Rebuild yesterday's raw-Python agent using LangChain, understand what\n",
    "> the framework automates, where it adds complexity, and what it hides from you.\n",
    "\n",
    "**Stack:** `langchain 1.3.x` · `langchain-anthropic 1.4.x` · `pydantic 2.x`  \n",
    "**Model:** `claude-3-5-haiku-20241022`\n",
    "\n",
    "```bash\n",
    "pip install langchain langchain-anthropic pydantic python-dotenv\n",
    "```\n",
]))

# ── SETUP ─────────────────────────────────────────────────────────────────────
cells.append(md_cell(["## Setup & Concept Mapping\n"]))
cells.append(code_cell([
    "import os, json, math, csv, warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "from pathlib import Path\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "# Load API key from project.env\n",
    "load_dotenv('project.env')\n",
    "\n",
    "# LangChain imports\n",
    "import langchain, langchain_anthropic\n",
    "from langchain_anthropic import ChatAnthropic\n",
    "from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder\n",
    "from langchain_core.messages import HumanMessage, AIMessage, SystemMessage\n",
    "from langchain_core.tools import tool\n",
    "from langchain_core.output_parsers import StrOutputParser, JsonOutputParser\n",
    "from langchain_core.runnables import RunnablePassthrough\n",
    "from langchain.agents import create_tool_calling_agent, AgentExecutor\n",
    "from langchain.memory import ConversationBufferMemory\n",
    "from langchain_core.runnables.history import RunnableWithMessageHistory\n",
    "from langchain_community.chat_message_histories import ChatMessageHistory\n",
    "from pydantic import BaseModel, Field\n",
    "\n",
    "print(f'langchain          : {langchain.__version__}')\n",
    "print(f'langchain-anthropic: {langchain_anthropic.__version__}')\n",
    "print(f'API key set        : {bool(os.environ.get(\"ANTHROPIC_API_KEY\"))}')\n",
    "\n",
    "MODEL = 'claude-3-5-haiku-20241022'\n",
    "llm   = ChatAnthropic(model=MODEL, temperature=0)\n",
    "print(f'LLM ready: {MODEL}')\n",
]))

cells.append(md_cell([
    "### Day 1 → Day 2 Concept Mapping\n",
    "\n",
    "| Raw Python (Day 1) | LangChain (Day 2) | What it does |\n",
    "|---|---|---|\n",
    "| `anthropic.Anthropic()` + `messages.create()` | `ChatAnthropic(model=...)` | LLM wrapper with retry/streaming built in |\n",
    "| `TOOL_SCHEMAS` + `execute_tool()` | `@tool` decorator | Schema auto-generated from function signature + docstring |\n",
    "| `while` loop + manual history append | `AgentExecutor` | ReAct loop, tool dispatch, error handling |\n",
    "| `agent.conversation_history` list | `ConversationBufferMemory` / `RunnableWithMessageHistory` | Persistent cross-turn context |\n",
    "| `log_step()` print statements | `verbose=True` in `AgentExecutor` | Reasoning trace |\n",
    "| `shap.Explanation` / manual parsing | Pydantic `BaseModel` + `.with_structured_output()` | Typed, validated output |\n",
]))

# ── TASK 1: LCEL ──────────────────────────────────────────────────────────────
cells.append(md_cell([
    "---\n",
    "## Task 1: LangChain Setup & LCEL Chains\n",
    "\n",
    "### What is LCEL's `|` pipe syntax?\n",
    "\n",
    "> The pipe operator (`|`) composes `Runnable` objects into a sequential chain.\n",
    "> Each component — prompt, LLM, parser — implements a `Runnable` interface with\n",
    "> an `invoke(input) -> output` method. `A | B` creates a new `Runnable` that calls\n",
    "> `B.invoke(A.invoke(input))` under the hood, passing the output of `A` as the\n",
    "> input of `B`. This gives you lazy evaluation, automatic streaming support, and\n",
    "> built-in async/batch/retry without any extra code.\n",
]))
cells.append(code_cell([
    "# ── Simple LCEL chain: prompt | llm | parser ─────────────────────────────────\n",
    "from langchain_core.prompts import PromptTemplate\n",
    "\n",
    "simple_prompt = PromptTemplate.from_template(\n",
    "    'You are a helpful tech advisor. Answer concisely in 1-2 sentences.\\n'\n",
    "    'Question: {question}'\n",
    ")\n",
    "\n",
    "# LCEL pipe: prompt -> LLM -> string parser\n",
    "simple_chain = simple_prompt | llm | StrOutputParser()\n",
    "\n",
    "response = simple_chain.invoke({'question': 'What makes a good laptop for data science?'})\n",
    "print('LCEL chain response:')\n",
    "print(response)\n",
]))

cells.append(code_cell([
    "# ── Multi-step LCEL chain (chaining two prompts) ─────────────────────────────\n",
    "summarise_prompt = ChatPromptTemplate.from_template(\n",
    "    'Summarise this tech advice in exactly one bullet point: {advice}'\n",
    ")\n",
    "\n",
    "# Chain: question -> advice -> one-line summary\n",
    "full_chain = (\n",
    "    {'advice': simple_chain}\n",
    "    | summarise_prompt\n",
    "    | llm\n",
    "    | StrOutputParser()\n",
    ")\n",
    "\n",
    "summary = full_chain.invoke({'question': 'What makes a good laptop for data science?'})\n",
    "print('Two-step LCEL chain:')\n",
    "print(summary)\n",
]))

# ── TASK 2: TOOLS ─────────────────────────────────────────────────────────────
cells.append(md_cell([
    "---\n",
    "## Task 2: Define & Register Tools with `@tool`\n",
    "\n",
    "**How docstrings work as prompts:** LangChain extracts the function's docstring\n",
    "and uses it verbatim as the tool's `description` field in the schema sent to the LLM.\n",
    "This is exactly the same as the `description` key in our Day 1 JSON schemas —\n",
    "the model selects which tool to call based *entirely* on this text. Vague or\n",
    "missing docstrings cause unreliable tool selection.\n",
]))
cells.append(code_cell([
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "# Tool 1: Calculator (reused from Day 1, now via @tool)\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "@tool\n",
    "def calculator(expression: str) -> str:\n",
    "    \"\"\"\n",
    "    Evaluates a mathematical expression and returns the numeric result.\n",
    "    Supports: +, -, *, /, ** (exponentiation), parentheses, and math functions\n",
    "    including sqrt(), abs(), round(), log(), sin(), cos(), pi, and e.\n",
    "    Use this tool whenever a numeric calculation is needed.\n",
    "    Examples: '2 + 2', 'sqrt(144)', '(3.14 * 5**2)', 'log(100, 10)'\n",
    "    \"\"\"\n",
    "    safe_globals = {\n",
    "        '__builtins__': {},\n",
    "        'abs': abs, 'round': round,\n",
    "        'sqrt': math.sqrt, 'log': math.log, 'log10': math.log10,\n",
    "        'sin': math.sin, 'cos': math.cos, 'tan': math.tan,\n",
    "        'floor': math.floor, 'ceil': math.ceil,\n",
    "        'pi': math.pi, 'e': math.e, 'pow': pow,\n",
    "    }\n",
    "    try:\n",
    "        return str(eval(expression.strip(), safe_globals))  # noqa: S307\n",
    "    except ZeroDivisionError:\n",
    "        return 'ERROR: division by zero'\n",
    "    except Exception as exc:\n",
    "        return f'ERROR: could not evaluate \"{expression}\": {exc}'\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "# Tool 2: Weather stub (reused from Day 1)\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "_WEATHER_DB = {\n",
    "    'karachi':   {'temp_c': 34, 'condition': 'Hot and sunny',   'humidity': 65},\n",
    "    'lahore':    {'temp_c': 38, 'condition': 'Very hot, hazy',  'humidity': 45},\n",
    "    'islamabad': {'temp_c': 28, 'condition': 'Partly cloudy',   'humidity': 55},\n",
    "    'london':    {'temp_c': 17, 'condition': 'Overcast',        'humidity': 78},\n",
    "    'new york':  {'temp_c': 24, 'condition': 'Sunny',           'humidity': 60},\n",
    "    'tokyo':     {'temp_c': 29, 'condition': 'Warm and humid',  'humidity': 80},\n",
    "    'dubai':     {'temp_c': 41, 'condition': 'Extremely hot',   'humidity': 50},\n",
    "    'paris':     {'temp_c': 20, 'condition': 'Mild and cloudy', 'humidity': 70},\n",
    "    'sydney':    {'temp_c': 15, 'condition': 'Cool and breezy', 'humidity': 62},\n",
    "    'toronto':   {'temp_c': 22, 'condition': 'Sunny',           'humidity': 58},\n",
    "}\n",
    "\n",
    "@tool\n",
    "def get_weather(city: str) -> str:\n",
    "    \"\"\"\n",
    "    Returns current temperature (Celsius) and weather conditions for a city.\n",
    "    This is a simulated stub — no real API key needed.\n",
    "    Use this tool for any question about current weather or temperature comparisons.\n",
    "    Supported cities: Karachi, Lahore, Islamabad, London, New York, Tokyo,\n",
    "    Dubai, Paris, Sydney, Toronto.\n",
    "    \"\"\"\n",
    "    key  = city.strip().lower()\n",
    "    data = _WEATHER_DB.get(key)\n",
    "    if data is None:\n",
    "        # partial match\n",
    "        for k, v in _WEATHER_DB.items():\n",
    "            if k in key or key in k:\n",
    "                data, key = v, k\n",
    "                break\n",
    "    if data is None:\n",
    "        return (f'ERROR: no weather data for \"{city}\". '\n",
    "                f'Available: {\", \".join(c.title() for c in _WEATHER_DB)}')\n",
    "    return (f'{key.title()}: {data[\"temp_c\"]}°C, {data[\"condition\"]}, '\n",
    "            f'humidity {data[\"humidity\"]}%')\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "# Tool 3: Product lookup from local JSON database (NEW — real data source)\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "PRODUCTS_PATH = Path('products.json')\n",
    "\n",
    "@tool\n",
    "def lookup_product(query: str) -> str:\n",
    "    \"\"\"\n",
    "    Searches a local product database (products.json) for electronics products.\n",
    "    Returns price, rating, brand, and stock for matching products.\n",
    "    Use this tool when the user asks about product prices, ratings, comparisons,\n",
    "    or recommendations for smartphones, laptops, tablets, headphones, or smartwatches.\n",
    "    Pass the product name or category as the query string.\n",
    "    Examples: 'iPhone 15 Pro', 'laptop', 'headphones under 300', 'Apple'\n",
    "    \"\"\"\n",
    "    try:\n",
    "        products = json.loads(PRODUCTS_PATH.read_text(encoding='utf-8'))\n",
    "    except Exception as exc:\n",
    "        return f'ERROR: could not load product database: {exc}'\n",
    "\n",
    "    q = query.strip().lower()\n",
    "    # Filter by name, category, or brand\n",
    "    matches = [\n",
    "        p for p in products\n",
    "        if q in p['name'].lower()\n",
    "        or q in p['category'].lower()\n",
    "        or q in p['brand'].lower()\n",
    "    ]\n",
    "\n",
    "    # Handle 'under N' price filter\n",
    "    import re\n",
    "    price_match = re.search(r'under\\s+(\\d+)', q)\n",
    "    if price_match:\n",
    "        limit   = int(price_match.group(1))\n",
    "        cat_q   = re.sub(r'under\\s+\\d+', '', q).strip()\n",
    "        matches = [\n",
    "            p for p in products\n",
    "            if p['price'] <= limit\n",
    "            and (not cat_q or cat_q in p['name'].lower()\n",
    "                 or cat_q in p['category'].lower()\n",
    "                 or cat_q in p['brand'].lower())\n",
    "        ]\n",
    "\n",
    "    if not matches:\n",
    "        return f'No products found matching \"{query}\". Try a category or brand name.'\n",
    "\n",
    "    lines = []\n",
    "    for p in matches[:5]:   # cap at 5 results\n",
    "        lines.append(\n",
    "            f\"- {p['name']} | ${p['price']} | Rating: {p['rating']}/5 \"\n",
    "            f\"| Brand: {p['brand']} | Stock: {p['stock']} units\"\n",
    "        )\n",
    "    return f'Found {len(matches)} product(s):\\n' + '\\n'.join(lines)\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "# Tool 4: CSV reader (reads products.csv — real data source)\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "@tool\n",
    "def read_product_csv(category: str = '') -> str:\n",
    "    \"\"\"\n",
    "    Reads the products.csv file and returns product data.\n",
    "    Optionally filters by category (e.g. 'Laptop', 'Smartphone', 'Headphones').\n",
    "    Use this tool when the user wants a full category listing or to see all products.\n",
    "    Returns columns: product_name, category, price_usd, rating, brand, in_stock.\n",
    "    \"\"\"\n",
    "    csv_path = Path('products.csv')\n",
    "    if not csv_path.exists():\n",
    "        return 'ERROR: products.csv not found.'\n",
    "    try:\n",
    "        rows = []\n",
    "        with open(csv_path, newline='', encoding='utf-8') as f:\n",
    "            reader = csv.DictReader(f)\n",
    "            for row in reader:\n",
    "                if not category or category.lower() in row['category'].lower():\n",
    "                    rows.append(row)\n",
    "        if not rows:\n",
    "            return f'No products found in category \"{category}\".'\n",
    "        header = '| Name | Category | Price | Rating | Brand |'\n",
    "        sep    = '|---|---|---|---|---|'\n",
    "        lines  = [header, sep]\n",
    "        for r in rows:\n",
    "            lines.append(\n",
    "                f\"| {r['product_name']} | {r['category']} | ${r['price_usd']} \"\n",
    "                f\"| {r['rating']} | {r['brand']} |\"\n",
    "            )\n",
    "        return '\\n'.join(lines)\n",
    "    except Exception as exc:\n",
    "        return f'ERROR reading CSV: {exc}'\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "# Tool 5: Flaky tool for error handling demo (Task 5)\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "import random\n",
    "_flaky_call_count = 0\n",
    "\n",
    "@tool\n",
    "def get_exchange_rate(currency_pair: str) -> str:\n",
    "    \"\"\"\n",
    "    Returns the exchange rate for a currency pair like 'USD/PKR' or 'EUR/USD'.\n",
    "    WARNING: This tool is simulated and may occasionally return an error\n",
    "    to demonstrate error handling. If it fails, try calling it again.\n",
    "    Format: 'BASE/QUOTE' e.g. 'USD/PKR', 'EUR/GBP', 'USD/EUR'\n",
    "    \"\"\"\n",
    "    global _flaky_call_count\n",
    "    _flaky_call_count += 1\n",
    "    # Fail on first call to simulate transient error\n",
    "    if _flaky_call_count == 1:\n",
    "        raise ConnectionError('Exchange rate API timeout (simulated). Please retry.')\n",
    "\n",
    "    rates = {\n",
    "        'USD/PKR': 278.5, 'PKR/USD': 0.0036,\n",
    "        'USD/EUR': 0.92,  'EUR/USD': 1.09,\n",
    "        'USD/GBP': 0.79,  'GBP/USD': 1.27,\n",
    "        'EUR/GBP': 0.86,  'GBP/EUR': 1.16,\n",
    "    }\n",
    "    pair = currency_pair.strip().upper()\n",
    "    rate = rates.get(pair)\n",
    "    if rate is None:\n",
    "        return f'ERROR: unknown pair \"{pair}\". Available: {\", \".join(rates.keys())}'\n",
    "    return f'1 {pair.split(\"/\")[0]} = {rate} {pair.split(\"/\")[1]}'\n",
    "\n",
    "\n",
    "ALL_TOOLS = [calculator, get_weather, lookup_product, read_product_csv, get_exchange_rate]\n",
    "print('Tools registered:')\n",
    "for t in ALL_TOOLS:\n",
    "    print(f'  {t.name:22s} — {t.description[:70]}...')\n",
]))

# ── TASK 3: AGENT ─────────────────────────────────────────────────────────────
cells.append(md_cell([
    "---\n",
    "## Task 3: Build Agent with `create_tool_calling_agent` + `AgentExecutor`\n",
]))
cells.append(code_cell([
    "# ── System prompt ─────────────────────────────────────────────────────────────\n",
    "system_prompt = \"\"\"\n",
    "You are a helpful tech product advisor with access to a product database,\n",
    "weather data, a calculator, and currency tools. Think step-by-step.\n",
    "Call one tool at a time, wait for the result, then decide what to do next.\n",
    "When you have enough information, give a clear, concise final answer.\n",
    "\"\"\"\n",
    "\n",
    "prompt = ChatPromptTemplate.from_messages([\n",
    "    ('system', system_prompt),\n",
    "    MessagesPlaceholder(variable_name='chat_history', optional=True),\n",
    "    ('human', '{input}'),\n",
    "    MessagesPlaceholder(variable_name='agent_scratchpad'),\n",
    "])\n",
    "\n",
    "# ── Wire agent ─────────────────────────────────────────────────────────────────\n",
    "agent = create_tool_calling_agent(llm, ALL_TOOLS, prompt)\n",
    "agent_executor = AgentExecutor(\n",
    "    agent=agent,\n",
    "    tools=ALL_TOOLS,\n",
    "    verbose=True,          # prints full reasoning trace\n",
    "    max_iterations=10,     # safeguard against infinite loops\n",
    "    handle_parsing_errors=True,\n",
    "    return_intermediate_steps=True,\n",
    ")\n",
    "print('AgentExecutor ready.')\n",
]))

cells.append(md_cell(["### Test 1: Single tool — calculator\n"]))
cells.append(code_cell([
    "result = agent_executor.invoke({'input': 'What is sqrt(225) + 15 squared?', 'chat_history': []})\n",
    "print('\\nFINAL ANSWER:', result['output'])\n",
]))

cells.append(md_cell(["### Test 2: Multi-step — 2 weather lookups + comparison\n"]))
cells.append(code_cell([
    "result2 = agent_executor.invoke({\n",
    "    'input': 'Look up the temperature in Karachi and London. Which is warmer and by how many degrees?',\n",
    "    'chat_history': []\n",
    "})\n",
    "print('\\nFINAL ANSWER:', result2['output'])\n",
]))

cells.append(md_cell(["### Test 3: Product lookup from real data (JSON database)\n"]))
cells.append(code_cell([
    "result3 = agent_executor.invoke({\n",
    "    'input': 'Find the price of the iPhone 15 Pro and Samsung Galaxy S24. Which is cheaper?',\n",
    "    'chat_history': []\n",
    "})\n",
    "print('\\nFINAL ANSWER:', result3['output'])\n",
]))

cells.append(md_cell([
    "### Annotated Reasoning Trace\n",
    "\n",
    "The `verbose=True` output shows LangChain's version of the ReAct pattern:\n",
    "\n",
    "```\n",
    "> Entering new AgentExecutor chain...\n",
    "\n",
    "[REASON]  The model reads the full prompt + history and decides what to do:\n",
    "          \"I need to look up the iPhone 15 Pro price first...\"\n",
    "\n",
    "[ACT]     Invoking: `lookup_product` with `{'query': 'iPhone 15 Pro'}`\n",
    "          ↳ LangChain formats this as a tool_use API call automatically\n",
    "\n",
    "[OBSERVE] Tool returned: \"- iPhone 15 Pro | $999 | Rating: 4.7/5 | Brand: Apple\"\n",
    "          ↳ LangChain appends this as a tool_result message automatically\n",
    "\n",
    "[REASON]  Now looks up Samsung Galaxy S24...\n",
    "[ACT]     Invoking: `lookup_product` with `{'query': 'Samsung Galaxy S24'}`\n",
    "[OBSERVE] Tool returned: \"- Samsung Galaxy S24 | $799 ...\"\n",
    "\n",
    "[REASON]  Both prices retrieved. S24 is $200 cheaper. Generate final answer.\n",
    "\n",
    "> Finished chain.\n",
    "```\n",
    "\n",
    "**vs Day 1 raw-Python:**\n",
    "- **Similar:** same Reason→Act→Observe loop; same tool_use / tool_result blocks under the hood\n",
    "- **Hidden now:** message history management (no manual append); tool schema generation;\n",
    "  stop_reason checking; error wrapping; the Anthropic API call itself\n",
    "- **Gained:** `verbose=True` trace; `max_iterations`; `handle_parsing_errors`;\n",
    "  `return_intermediate_steps` — all free from the framework\n",
]))

# ── TASK 4: MEMORY ────────────────────────────────────────────────────────────
cells.append(md_cell([
    "---\n",
    "## Task 4: Add Conversation Memory\n",
    "\n",
    "Using `RunnableWithMessageHistory` (modern LangChain pattern) to persist\n",
    "conversation across turns so the agent handles follow-up questions.\n",
]))
cells.append(code_cell([
    "# ── Session store (in-memory; swap for Redis in production) ──────────────────\n",
    "session_store: dict[str, ChatMessageHistory] = {}\n",
    "\n",
    "def get_session_history(session_id: str) -> ChatMessageHistory:\n",
    "    if session_id not in session_store:\n",
    "        session_store[session_id] = ChatMessageHistory()\n",
    "    return session_store[session_id]\n",
    "\n",
    "# ── Wrap agent executor with history ─────────────────────────────────────────\n",
    "agent_with_memory = RunnableWithMessageHistory(\n",
    "    agent_executor,\n",
    "    get_session_history,\n",
    "    input_messages_key='input',\n",
    "    history_messages_key='chat_history',\n",
    "    output_messages_key='output',\n",
    ")\n",
    "\n",
    "SESSION = 'demo-session-1'\n",
    "config  = {'configurable': {'session_id': SESSION}}\n",
    "\n",
    "print('Memory-enabled agent ready. Session:', SESSION)\n",
]))

cells.append(md_cell(["### 3-Turn Conversation Test\n"]))
cells.append(code_cell([
    "# Turn 1: Find a product price\n",
    "print('='*60)\n",
    "print('TURN 1')\n",
    "print('='*60)\n",
    "r1 = agent_with_memory.invoke(\n",
    "    {'input': 'What is the price of the Sony WH-1000XM5 headphones?'},\n",
    "    config=config\n",
    ")\n",
    "print('Assistant:', r1['output'])\n",
]))

cells.append(code_cell([
    "# Turn 2: Follow-up using context from Turn 1\n",
    "print('='*60)\n",
    "print('TURN 2 (agent remembers Turn 1)')\n",
    "print('='*60)\n",
    "r2 = agent_with_memory.invoke(\n",
    "    {'input': 'Now compare it to the Apple AirPods Pro 2. Which has a better rating?'},\n",
    "    config=config\n",
    ")\n",
    "print('Assistant:', r2['output'])\n",
]))

cells.append(code_cell([
    "# Turn 3: Decision based on previous 2 turns\n",
    "print('='*60)\n",
    "print('TURN 3 (agent uses full conversation context)')\n",
    "print('='*60)\n",
    "r3 = agent_with_memory.invoke(\n",
    "    {'input': 'Which one should I recommend to a budget-conscious client who still wants great quality?'},\n",
    "    config=config\n",
    ")\n",
    "print('Assistant:', r3['output'])\n",
]))

cells.append(code_cell([
    "# Show accumulated memory\n",
    "history = get_session_history(SESSION)\n",
    "print(f'\\nConversation history: {len(history.messages)} messages stored')\n",
    "for i, msg in enumerate(history.messages):\n",
    "    role = 'Human' if isinstance(msg, HumanMessage) else 'AI'\n",
    "    print(f'  [{i}] {role}: {str(msg.content)[:80]}...')\n",
]))

# ── TASK 5: STRUCTURED OUTPUT + ERROR HANDLING ────────────────────────────────
cells.append(md_cell([
    "---\n",
    "## Task 5: Structured Output & Error Handling\n",
    "\n",
    "### 5a. Structured Output with Pydantic\n",
]))
cells.append(code_cell([
    "# ── Pydantic schema for structured product recommendation ────────────────────\n",
    "class ProductRecommendation(BaseModel):\n",
    "    product_name:  str          = Field(description='Full product name')\n",
    "    price_usd:     float        = Field(description='Price in US dollars')\n",
    "    rating:        float        = Field(description='Rating out of 5.0')\n",
    "    reason:        str          = Field(description='1-2 sentence recommendation rationale')\n",
    "    verdict:       str          = Field(description='One of: Recommended, Not Recommended, Budget Pick')\n",
    "    pros:          list[str]    = Field(description='Up to 3 key strengths')\n",
    "    cons:          list[str]    = Field(description='Up to 2 key weaknesses')\n",
    "\n",
    "\n",
    "# ── Structured output chain (LCEL) ────────────────────────────────────────────\n",
    "struct_prompt = ChatPromptTemplate.from_messages([\n",
    "    ('system',\n",
    "     'You are a product analyst. Given the product info below, produce a '\n",
    "     'structured recommendation. Be specific and concise.'),\n",
    "    ('human', 'Product info:\\n{product_info}\\n\\nUser budget: {budget}'),\n",
    "])\n",
    "\n",
    "structured_llm    = llm.with_structured_output(ProductRecommendation)\n",
    "structured_chain  = struct_prompt | structured_llm\n",
    "\n",
    "# First look up the product, then structure the recommendation\n",
    "product_info = lookup_product.invoke({'query': 'MacBook Air M3'})\n",
    "recommendation = structured_chain.invoke({\n",
    "    'product_info': product_info,\n",
    "    'budget': '$1500'\n",
    "})\n",
    "\n",
    "print('Structured Recommendation:')\n",
    "print(f'  Product : {recommendation.product_name}')\n",
    "print(f'  Price   : ${recommendation.price_usd}')\n",
    "print(f'  Rating  : {recommendation.rating}/5')\n",
    "print(f'  Verdict : {recommendation.verdict}')\n",
    "print(f'  Reason  : {recommendation.reason}')\n",
    "print(f'  Pros    : {recommendation.pros}')\n",
    "print(f'  Cons    : {recommendation.cons}')\n",
    "print(f'\\nType: {type(recommendation).__name__} (validated Pydantic model)')\n",
]))

cells.append(md_cell(["### 5b. Error Handling — Flaky Tool Recovery\n"]))
cells.append(code_cell([
    "# Reset flaky call counter so it fails on first call again\n",
    "import importlib; import sys\n",
    "_flaky_call_count = 0  # reset manually since it's in notebook scope\n",
    "\n",
    "# AgentExecutor with handle_parsing_errors=True also handles tool exceptions\n",
    "# by catching them and returning the error as a tool observation\n",
    "flaky_executor = AgentExecutor(\n",
    "    agent=create_tool_calling_agent(llm, [get_exchange_rate, calculator], prompt),\n",
    "    tools=[get_exchange_rate, calculator],\n",
    "    verbose=True,\n",
    "    max_iterations=5,\n",
    "    handle_parsing_errors=True,\n",
    ")\n",
    "\n",
    "print('Testing flaky tool (will fail on first call, succeed on retry)...')\n",
    "try:\n",
    "    flaky_result = flaky_executor.invoke({\n",
    "        'input': 'What is the USD to PKR exchange rate?',\n",
    "        'chat_history': []\n",
    "    })\n",
    "    print('\\nFINAL:', flaky_result['output'])\n",
    "except Exception as e:\n",
    "    print(f'Agent gave up after max_iterations: {e}')\n",
]))

cells.append(md_cell([
    "### 5c. Reflection: LangChain vs Raw Python\n",
    "\n",
    "> **What LangChain made easier:**\n",
    "> - Tool schemas are auto-generated from `@tool` docstrings — no manual JSON writing\n",
    "> - Memory, message history append, and stop_reason checking are invisible\n",
    "> - `return_intermediate_steps=True` gives you the full trace without custom logging\n",
    "> - Structured output (`with_structured_output`) handles JSON parsing + Pydantic validation\n",
    "\n",
    "> **Abstraction leakiness / 'magic' noticed:**\n",
    "> - `RunnableWithMessageHistory` requires matching `input_messages_key` /\n",
    ">   `history_messages_key` / `output_messages_key` exactly to your prompt variables —\n",
    ">   mismatches fail silently with confusing errors\n",
    "> - `handle_parsing_errors=True` swallows tool exceptions and turns them into\n",
    ">   observations — good for recovery, bad for debugging if you don't check verbose output\n",
    "> - LCEL's `|` pipe is elegant but type errors (e.g. a `dict` when a `str` is expected)\n",
    ">   only surface at `invoke()` time, not at chain definition time\n",
    "> - The framework version has more moving parts (7 imports vs 2) and more things\n",
    ">   to configure correctly before it works at all\n",
]))

# ── WRITE-UP SUMMARY ──────────────────────────────────────────────────────────
cells.append(md_cell([
    "---\n",
    "## Summary: Raw Python vs LangChain\n",
    "\n",
    "| Aspect | Day 1 Raw Python | Day 2 LangChain |\n",
    "|---|---|---|\n",
    "| Tool schema | Manual JSON dict | Auto from `@tool` docstring |\n",
    "| ReAct loop | `while` + manual append | `AgentExecutor` |\n",
    "| Memory | `conversation_history` list | `RunnableWithMessageHistory` |\n",
    "| Structured output | Manual JSON parsing | `with_structured_output(PydanticModel)` |\n",
    "| Error handling | `try/except` in runner | `handle_parsing_errors=True` |\n",
    "| Debug visibility | Full (your own logs) | `verbose=True` (framework-controlled) |\n",
    "| Lines of code | ~150 | ~80 (agent) + ~100 (tools) |\n",
    "| Mental model required | High (you see everything) | Medium (framework hides details) |\n",
    "\n",
    "**Conclusion:** LangChain reduces boilerplate significantly but trades away transparency.\n",
    "Knowing Day 1's raw loop makes you a much better LangChain debugger — you know\n",
    "what's happening inside `AgentExecutor` when things go wrong.\n",
]))

# ── Assemble notebook ─────────────────────────────────────────────────────────
nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3 (venv)",
            "language": "python",
            "name": "python3"
        },
        "language_info": {"name": "python", "version": "3.13.0"}
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

out = r'd:\Netixsol_Internship\netixsol_internship\Week-5\day-2\code.ipynb'
with open(out, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print(f'Notebook written: {out}  ({len(cells)} cells)')
