"""Patch SHAP cells (18 and 19) in Day 5 notebook to fix the waterfall TypeError."""
import json

path = r'd:\Netixsol_Internship\netixsol_internship\Week-4\day-5\code.ipynb'
with open(path, encoding='utf-8') as f:
    nb = json.load(f)

# ── Fix Cell 18: SHAP global summary ─────────────────────────────────────────
# Root cause: shap_values() returns list [neg, pos] for binary classification;
#             must select [1] for the positive class before summary_plot.
nb['cells'][18]['source'] = [
    "# SHAP global summary\n",
    "if SHAP_OK:\n",
    "    print('Computing SHAP values (TreeExplainer on HGB)...')\n",
    "    explainer = shap.TreeExplainer(clf)\n",
    "    X_shap    = X_test_trans[:200]\n",
    "\n",
    "    # Binary classification: shap_values() returns [neg_class_arr, pos_class_arr]\n",
    "    # Always use index [1] for the positive class (>50K)\n",
    "    shap_vals_raw = explainer.shap_values(X_shap)\n",
    "    if isinstance(shap_vals_raw, list):\n",
    "        shap_vals_pos = shap_vals_raw[1]       # positive-class SHAP matrix\n",
    "        base_val      = float(explainer.expected_value[1])\n",
    "    else:\n",
    "        # Some SHAP versions return a single array for binary\n",
    "        shap_vals_pos = shap_vals_raw\n",
    "        ev = explainer.expected_value\n",
    "        base_val = float(ev) if np.ndim(ev) == 0 else float(ev[1])\n",
    "\n",
    "    print(f'SHAP base value (E[f(x)] for >50K class): {base_val:.4f}')\n",
    "\n",
    "    plt.figure(figsize=(10, 7))\n",
    "    shap.summary_plot(\n",
    "        shap_vals_pos, X_shap,\n",
    "        feature_names=feat_names,\n",
    "        max_display=15,\n",
    "        show=False\n",
    "    )\n",
    "    plt.title('SHAP Summary Plot -- HistGradientBoosting (positive class)')\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "else:\n",
    "    print('SHAP not installed. Run: pip install shap')\n",
]

# ── Fix Cell 19: SHAP local waterfall ─────────────────────────────────────────
# Root causes:
#   1. explainer.expected_value is an array for binary -> must extract scalar [1]
#   2. explainer.shap_values(instance) returns list -> must use [1][0] for pos class
#   3. shap.waterfall_plot is deprecated -> use shap.plots.waterfall
nb['cells'][19]['source'] = [
    "# SHAP local explanations -- 3 individuals (TP, FP, FN)\n",
    "\n",
    "proba_test  = final_model.predict_proba(X_test_raw)[:, 1]\n",
    "y_pred_test = (proba_test >= 0.5).astype(int)\n",
    "\n",
    "tp_mask = (y_pred_test == 1) & (y_test.values == 1)\n",
    "fp_mask = (y_pred_test == 1) & (y_test.values == 0)\n",
    "fn_mask = (y_pred_test == 0) & (y_test.values == 1)\n",
    "\n",
    "tp_idx = np.where(tp_mask)[0][0]\n",
    "fp_idx = np.where(fp_mask)[0][0]\n",
    "fn_idx = np.where(fn_mask)[0][0]\n",
    "\n",
    "X_test_eng_arr = engineer_features(X_test_raw)\n",
    "X_test_t       = preproc_fitted.transform(X_test_eng_arr)\n",
    "\n",
    "cases = {\n",
    "    'True Positive  (correctly predicted >50K)': tp_idx,\n",
    "    'False Positive (wrongly predicted >50K)':   fp_idx,\n",
    "    'False Negative (missed >50K earner)':       fn_idx,\n",
    "}\n",
    "\n",
    "if SHAP_OK:\n",
    "    # ── Resolve expected_value to a scalar ───────────────────────────────────\n",
    "    # TreeExplainer on binary classifiers returns array [neg_ev, pos_ev]\n",
    "    ev = explainer.expected_value\n",
    "    if hasattr(ev, '__len__'):\n",
    "        base_value_scalar = float(ev[1])   # positive class expected value\n",
    "    else:\n",
    "        base_value_scalar = float(ev)\n",
    "\n",
    "    for label, idx in cases.items():\n",
    "        instance = X_test_t[idx:idx+1]\n",
    "\n",
    "        # ── Resolve SHAP values to a 1-D vector for positive class ───────────\n",
    "        # shap_values() on a single row returns [neg_arr, pos_arr] for binary\n",
    "        sv_raw = explainer.shap_values(instance)\n",
    "        if isinstance(sv_raw, list):\n",
    "            sv = sv_raw[1][0]   # positive-class SHAP for this single row\n",
    "        else:\n",
    "            sv = sv_raw[0]      # already a 1-D array\n",
    "\n",
    "        top3_feat = pd.Series(np.abs(sv), index=feat_names).nlargest(3)\n",
    "        prob  = proba_test[idx]\n",
    "        truth = y_test.values[idx]\n",
    "\n",
    "        print(f'\\n--- {label} ---')\n",
    "        print(f'  Predicted prob: {prob:.3f}  |  True label: {truth}')\n",
    "        print(f'  Top-3 SHAP features: {list(top3_feat.index)}')\n",
    "\n",
    "        # Build Explanation: base_values MUST be a Python scalar\n",
    "        expl = shap.Explanation(\n",
    "            values=sv,\n",
    "            base_values=base_value_scalar,\n",
    "            data=instance[0],\n",
    "            feature_names=list(feat_names)\n",
    "        )\n",
    "        shap.plots.waterfall(expl, max_display=8, show=False)\n",
    "        plt.title(label)\n",
    "        plt.tight_layout()\n",
    "        plt.show()\n",
    "else:\n",
    "    print('SHAP not available -- showing raw feature values for each case.')\n",
    "    for label, idx in cases.items():\n",
    "        row = X_test_raw.iloc[idx]\n",
    "        print(f'\\n--- {label} ---')\n",
    "        print(f'  Predicted prob: {proba_test[idx]:.3f} | True label: {y_test.values[idx]}')\n",
    "        print(f'  age={row[\"age\"]}, education={row[\"education\"]}, '\n",
    "              f'occupation={row[\"occupation\"]}, capital-gain={row[\"capital-gain\"]}')\n",
    "\n",
    "print('''\n",
    "Plain-English Explanations:\n",
    "  True Positive : High capital gain + senior occupation drove this person firmly\n",
    "                  above the threshold -- model correctly predicts >50K.\n",
    "  False Positive: High education and long hours pushed probability above 0.5,\n",
    "                  but zero investment income means actual income is <=50K.\n",
    "  False Negative: Doctorate-level education is offset by very low hours and no\n",
    "                  capital gain -- model misses this true >50K earner.\n",
    "''')\n",
]

with open(path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print('Cells 18 and 19 patched successfully.')
