import asyncio
import os
from typing import AsyncGenerator, List, Dict
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from src.config.settings import settings

class LLMEngine:
    """
    Token-streaming LLM wrapper using Gemini 1.5 Flash for minimum latency.
    """
    def __init__(self, model: str = os.environ.get("LLM_MODEL", "nvidia/nemotron-4-340b-instruct"), temperature: float = 0.5):
        self.llm = ChatOpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=os.environ.get("OPENROUTER_API_KEY", ""),
            model=model, 
            temperature=temperature
        )
        
    async def generate_response_stream(self, system_prompt: str, history: List[Dict[str, str]]) -> AsyncGenerator[str, None]:
        """Streams tokens back immediately as they are generated by Gemini."""
        messages = [SystemMessage(content=system_prompt)]
        for msg in history:
            if msg["role"] == "user":
                messages.append(HumanMessage(content=msg["content"]))
            elif msg["role"] == "assistant":
                messages.append(AIMessage(content=msg["content"]))
                
        # Call Gemini's async streaming API
        async for chunk in self.llm.astream(messages):
            if chunk.content:
                yield chunk.content
